### ISSUE TITLE
This is nice but I need more details

### ISSUE THREAD

**Issue by MaZyGer** [russdreamer/instagram-followers-statistics#18]
Hi, I just used this and worked well. But I am not sure about why the script can access to my followers.

It seems like it uses my "logged in" session-information like token whatever and sends to a server. From there it uses that to receive the follower list? Via api? Its unclear. 

Well, this is the problem. It is not a garauntee for me what else could happen, because the script, even without me to be on my profile it still works on my private profile. I am afraid that it can be stolen or used for whatever. Not saying it will be used, but the danger is there.

That's why I would like to have more information. Why and how it can access to my follower list?

Also since instagram tries to stop **automation** so badly in last time and if it can understand my "account" requesting follower list often, so it also can do something against it.

**Comment by russdreamer** [comment]
Hi,
1. Instagram doesn't provide any API for that as Instagram tries to prevent any such an app. It used the same mechanism like if you'd perform opening your followers by clicking the button. It sends token data the same way as Instagram UI using the same REST queries as if you click buttons. 
2. It cannot use your data if you're not on the website. It can't even access instagram data being on another site, that is why it's not a standalone app and works only on the same Instagram page.
3. Is it possible your profile can be blocked by this app? Yes, as using any app for automation can be illegal. But it's more likely possible for actions like auto-subscription. This functionality is also available in this app but it will provide you a warning. However, the script will try to prevent any such a problem by server response analyzing (dozens of my accounts were blocked while testing and finding solutions).
4. I didn't get how your profile can be stolen. It can't get your password, Instagram doesn't store your password anywhere on your browser. It can access temporary token only. If we assume the script was aiming to steal your profile - it's not possible because token will be changed in a short period of time and to get the new one - it has to login with your email and password (which is unknown)
5. Can your data be used? Theoretically - yes. In practice - it doesn't. Everything that script gathers is described in ReadMe. Anonimased statistics about what buttons were clicked in the application (nothing about Instagram data). 
6. All the code source of script is open and provided in this repo as the script uses all the source directly from this GIT repo
7. That is why if Instagram changes its UI even a bit - I have to change a lot in my applications by reading their obfuscated code
